# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'YYS.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sys
from Func.untitled import  openMobil
from Func.huodong import zhounian
import adb

from threading import Thread
from time import sleep, ctime

from Func.base import save_img,start_yys,cv_test
from adb import save_sc

DEBUG = True
# DEBUG = False


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        # self.centralwidget.setObjectName("centralwidget")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 70, 93, 28))
        self.pushButton.setObjectName("pushButton")
        # self.pushButton.clicked.connect(self.btn_click_1)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 120, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        # self.pushButton_2.clicked.connect(self.btn_click_2)

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 170, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")


        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(280, 220, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")


        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(280, 270, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")


        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(280, 320, 93, 28))
        self.pushButton_6.setObjectName("pushButton_6")


        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(280, 370, 93, 28))
        self.pushButton_7.setObjectName("pushButton_7")


        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(280, 410, 93, 28))
        self.pushButton_8.setObjectName("pushButton_8")


        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(280, 450, 241, 81))
        self.textBrowser.setObjectName("textBrowser")


        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 70, 271, 371))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./pic/龙凤呈祥.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(520, 70, 271, 371))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("./pic/新年快乐.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(390, 70, 113, 21))
        self.lineEdit.setObjectName("lineEdit")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(390, 120, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(390, 170, 113, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(390, 220, 113, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(390, 270, 113, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")

        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(390, 320, 113, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")

        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(390, 370, 113, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")

        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(390, 410, 113, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; color:#ff0000;\">恭贺新禧</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ff0000;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "开启模拟器"))
        self.pushButton_2.setText(_translate("MainWindow", "截图"))
        self.pushButton_3.setText(_translate("MainWindow", "阴阳师启动"))
        self.pushButton_4.setText(_translate("MainWindow", "点击测试"))
        self.pushButton_5.setText(_translate("MainWindow", "识别测试"))
        self.pushButton_6.setText(_translate("MainWindow", "未定义5"))
        self.pushButton_7.setText(_translate("MainWindow", "未定义6"))
        self.pushButton_8.setText(_translate("MainWindow", "活动"))

    # def btn_click_1(self):
    #     if DEBUG : print('Btn1 Click')
    #     openMobil()
    #
    # def btn_click_2(self):
    #     if DEBUG : print('Btn2 Click')
    #     pic_name = self.lineEdit_2.text()
    #     save_img(pic_name)
    #
    # def btn_click_3(self):
    #     if DEBUG : print('Btn3 Click')
    #     start_yys()
    #
    # def btn_click_4(self):
    #     if DEBUG : print('Btn4 Click')
    #     x_v = self.lineEdit_3.text()
    #     y_v = self.lineEdit_4.text()
    #     adb.click(x_v, y_v)
    #     # adb.click(150, 1960)
    #
    #
    # def btn_click_5(self):
    #     if DEBUG : print('Btn5 Click')
    #     cv_test()
    #
    # def btn_click_6(self):
    #     if DEBUG : print('Btn6 Click')
    #
    # def btn_click_7(self):
    #     if DEBUG : print('Btn7 Click')
    #
    # def btn_click_8(self):
    #     err_flag = True #为真则正常调用方法，为假说明有异常
    #     if DEBUG : print('Btn8 Click')
    #     num1 = self.lineEdit_7.text()
    #     num2 = self.lineEdit_8.text()
    #     if num2 :
    #         try:
    #             num1 = int(num1)
    #             num2 = int(num2)
    #
    #         except:
    #             msg_box = QMessageBox(QMessageBox.Critical, '错误', '通关时间和次数仅能输入数字')
    #             msg_box.exec_()
    #             err_flag = False
    #     else:
    #         msg_box = QMessageBox(QMessageBox.Critical, '错误', '请输入通关时间')
    #         msg_box.exec_()
    #         err_flag = False
    #     if  err_flag :
    #         fight = Thread(target=zhounian(time=num1, need=num2), args=('战斗线程', 1))
    #         fight.start()




if __name__== "__main__":
    app = QtWidgets.QApplication(sys.argv)         # 创建一个QApplication，即将开发的软件app
    # fight = Thread()
    MainWindow = QtWidgets.QMainWindow()    #QMainWindow装载需要的组件
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)                                 #执行类中的setupUi方法
    MainWindow.show()
    sys.exit(app.exec_())                                     #exit()或点击按钮退出app